[2022-05-24 18:01:38] [WARNING]: 警告: 配置文件内的QQ号 (1233456) 与缓存内的QQ号 (2945339871) 不相同 
[2022-05-24 18:01:38] [WARNING]: 1. 使用会话缓存继续. 
[2022-05-24 18:01:38] [WARNING]: 2. 删除会话缓存并重启. 
[2022-05-24 18:01:38] [WARNING]: 请选择: (5秒后自动选1) 
[2022-05-24 18:02:39] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-24 18:04:34] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-24 18:04:37] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-24 18:04:54] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-24 18:09:29] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-24 18:09:32] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-24 18:09:36] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-24 18:09:40] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":116,"PacketSent":69,"PacketLost":0,"MessageReceived":25,"MessageSent":14,"LastMessageTime":1653386939,"DisconnectTimes":0,"LostTimes":0}},"time":1653386966}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-24 18:09:42] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-24 18:09:46] [WARNING]: 转换CQ码 [CQ:image,file=file:///c:/images/1653132382548.gif,url=file:///c:/images/1653132382548.gif] 时出现错误: file not found 将原样发送. 
[2022-05-24 18:09:46] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-24 18:09:50] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-24 18:09:54] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":116,"PacketSent":69,"PacketLost":0,"MessageReceived":25,"MessageSent":14,"LastMessageTime":1653386939,"DisconnectTimes":0,"LostTimes":0}},"time":1653386980}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-24 18:09:56] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-24 18:09:58] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-24 18:10:00] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-24 18:10:02] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-24 18:10:04] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-24 18:10:06] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-24 18:10:08] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":119,"PacketSent":71,"PacketLost":0,"MessageReceived":25,"MessageSent":15,"LastMessageTime":1653386939,"DisconnectTimes":0,"LostTimes":0}},"time":1653386994}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-24 18:10:10] [WARNING]: 上报 Event 数据 {"anonymous":null,"font":0,"group_id":588696648,"message":"坏了","message_id":-107463258,"message_seq":199896,"message_type":"group","post_type":"message","raw_message":"坏了","self_id":2945339871,"sender":{"age":0,"area":"","card":"care。","level":"","nickname":"Care。","role":"admin","sex":"unknown","title":"爸爸","user_id":646665585},"sub_type":"normal","time":1653386997,"user_id":646665585}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-24 18:10:10] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-24 18:10:14] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
[2022-05-24 18:10:18] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 3 次重试 
[2022-05-24 18:10:22] [WARNING]: 上报 Event 数据 {"interval":5000,"meta_event_type":"heartbeat","post_type":"meta_event","self_id":2945339871,"status":{"app_enabled":true,"app_good":true,"app_initialized":true,"good":true,"online":true,"plugins_good":null,"stat":{"PacketReceived":120,"PacketSent":71,"PacketLost":0,"MessageReceived":26,"MessageSent":15,"LastMessageTime":1653386996,"DisconnectTimes":0,"LostTimes":0}},"time":1653387008}
 到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 停止上报：已达重试上线 
[2022-05-24 18:10:24] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 1 次重试 
[2022-05-24 18:10:28] [WARNING]: 上报 Event 数据到 http://localhost:8400/ 失败: Post "http://localhost:8400/": dial tcp [::1]:8400: connectex: No connection could be made because the target machine actively refused it. 将进行第 2 次重试 
